---
spring:
  config:
    import:
      - optional:classpath:app.env[.properties]
---

spring:
  oracle:
    cloud:
      oci:
        s3:
          enabled: true
          namespace: ${OCI_S3_NAMESPACE}
          region: ${OCI_S3_REGION}
          access-key: ${OCI_S3_ACCESS_KEY}
          secret-key: ${OCI_S3_SECRET_KEY}
          default-bucket: ${OCI_S3_DEFAULT_BUCKET}
          path-style-access: true
          chunked-encoding-enabled: false
          checksum-validation-enabled: false
          health-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    ociS3:
      enabled: true